server:
  port: 8080

spring:
  application:
    name: ecommerce-ops-backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecommerce_ops?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173
      - http://47.96.135.116
